# Generated by Django 5.2.4 on 2025-08-09 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='annulee_par_collaborateur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='absence',
            name='motif_annulation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='validationhistorique',
            name='absence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='absences.absence'),
        ),
        migrations.AlterField(
            model_name='validationhistorique',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Recuperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField()),
                ('justificatif', models.FileField(upload_to='justificatifs_recuperations/')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
