# Generated by Django 5.2.3 on 2025-09-12 11:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validationhistorique',
            old_name='date_action',
            new_name='date_validation',
        ),
        migrations.RenameField(
            model_name='validationhistorique',
            old_name='commentaire',
            new_name='motif',
        ),
        migrations.RemoveField(
            model_name='validationhistorique',
            name='action',
        ),
        migrations.AddField(
            model_name='validationhistorique',
            name='decision',
            field=models.CharField(default=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='validationhistorique',
            name='role_valide',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='nombre_jours',
            field=models.DecimalField(decimal_places=1, help_text='Nombre total de jours ouvrés demandés (peut inclure des demi-journées)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='quotaabsence',
            name='jours_disponibles',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
