# Generated by Django 5.2.3 on 2025-09-15 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0002_rename_date_action_validationhistorique_date_validation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recuperation',
            name='date_debut',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recuperation',
            name='nombre_jours',
            field=models.DecimalField(decimal_places=1, default=1, help_text='Nombre total de jours de récupération (ex: 1, 1.5, 2)', max_digits=5),
        ),
    ]
