# Generated by Django 5.2.3 on 2025-09-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0003_recuperation_date_debut_recuperation_nombre_jours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuve_superieur', 'Approuvé par supérieur'), ('verifie_drh', 'Vérifié par DRH'), ('valide_dp', 'Validé par DP'), ('rejete', 'Rejeté'), ('annulee', 'Annulée par le collaborateur')], default='en_attente', max_length=30),
        ),
        migrations.AlterField(
            model_name='validationhistorique',
            name='decision',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
