# Generated by Django 5.2.3 on 2025-09-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0004_alter_absence_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationhistorique',
            name='decision',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='validationhistorique',
            name='role_valide',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
