# Generated by Django 5.2.3 on 2025-09-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0005_alter_validationhistorique_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recuperation',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recuperation',
            name='motif_annulation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recuperation',
            name='statut',
            field=models.CharField(default='en_attente', max_length=30),
        ),
    ]
