name: Build and deploy Python app to Azure Web App - gestionabsencesapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Export AZURE_POSTGRESQL_CONNECTIONSTRING
        run: echo "AZURE_POSTGRESQL_CONNECTIONSTRING=${{ secrets.AZURE_POSTGRESQL_CONNECTIONSTRING }}" >> $GITHUB_ENV

      - name: Export SECRET and WEBSITE_HOSTNAME
        run: |
          echo "SECRET=${{ secrets.SECRET }}" >> $GITHUB_ENV
          echo "WEBSITE_HOSTNAME=${{ secrets.WEBSITE_HOSTNAME }}" >> $GITHUB_ENV

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set environment variable for Django settings
        run: echo "DJANGO_SETTINGS_MODULE=gestion_absencesApp.deployment" >> $GITHUB_ENV

      - name: Run collectstatic
        run: python manage.py collectstatic --noinput

      - name: Run migrations
        run: python manage.py migrate

      # Optionnel : Créer un superuser (⚠️ À désactiver après premier déploiement)
      # - name: Create superuser
      #   run: |
      #     echo "from django.contrib.auth import get_user_model; \
      #     User = get_user_model(); \
      #     User.objects.filter(username='admin').exists() or \
      #     User.objects.create_superuser('admin', 'admin@example.com', '94649092@Hiy')" | python manage.py shell

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'gestionabsencesapp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_58DD4BB6D1DE472AA499D91E38ADCA1E }}
